# Generated by Django 3.2.9 on 2021-11-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdProduct', models.CharField(default='', max_length=20)),
                ('State', models.CharField(max_length=20)),
                ('AdType', models.CharField(max_length=20)),
                ('Price', models.IntegerField(max_length=20)),
                ('Style', models.CharField(max_length=15)),
                ('Clothing', models.CharField(max_length=50)),
                ('Shoes', models.CharField(max_length=50)),
                ('Size', models.CharField(max_length=20)),
                ('MaleFemale', models.BooleanField(default=False)),
                ('Height', models.IntegerField(max_length=10)),
                ('Color', models.CharField(default='', max_length=100)),
                ('Location', models.CharField(default='', max_length=100)),
                ('Photos', models.FileField(default=0, upload_to='')),
            ],
        ),
    ]
