from rest_framework import serializers

from .models import Product

class ProductSerializer(serializers.Serializer): # сериалайзер для одного товара

    IdProduct = serializers.CharField(max_length=20, default='')
    State = serializers.CharField(max_length=20)
    AdType = serializers.CharField(max_length=20)
    Price = serializers.IntegerField()
    Style = serializers.CharField(max_length=15)
    Clothing = serializers.CharField(max_length=50)
    Shoes = serializers.CharField(max_length=50)
    Size = serializers.CharField(max_length=20)
    MaleFemale = serializers.CharField(max_length=20)
    Height = serializers.IntegerField()
    Color = serializers.CharField(max_length=100, default='')
    Location = serializers.CharField(max_length=100, default='')
    Photo_1 = serializers.ImageField(default=None)
    Photo_2 = serializers.ImageField(default=None)
    Photo_3 = serializers.ImageField(default=None)
    Photo_4 = serializers.ImageField(default=None)
    Photo_5 = serializers.ImageField(default=None)
    Photo_6 = serializers.ImageField(default=None)
    Photo_7 = serializers.ImageField(default=None)
    Photo_8 = serializers.ImageField(default=None)
    Photo_9 = serializers.ImageField(default=None)
    Photo_10 = serializers.ImageField(default=None)
    Photo_11 = serializers.ImageField(default=None)
    Photo_12 = serializers.ImageField(default=None)
    Photo_13 = serializers.ImageField(default=None)
    Photo_14 = serializers.ImageField(default=None)
    Photo_15 = serializers.ImageField(default=None)
    Photo_16 = serializers.ImageField(default=None)
    Photo_17 = serializers.ImageField(default=None)
    Photo_18 = serializers.ImageField(default=None)
    Photo_19 = serializers.ImageField(default=None)
    Photo_20 = serializers.ImageField(default=None)
    Photo_21 = serializers.ImageField(default=None)
    Photo_22 = serializers.ImageField(default=None)
    Photo_23 = serializers.ImageField(default=None)
    Photo_24 = serializers.ImageField(default=None)
    Photo_25 = serializers.ImageField(default=None)
    Photo_26 = serializers.ImageField(default=None)
    Photo_27 = serializers.ImageField(default=None)
    Photo_28 = serializers.ImageField(default=None)
    Photo_29 = serializers.ImageField(default=None)
    Photo_30 = serializers.ImageField(default=None)
    Video = serializers.CharField(default='', max_length=1000)
    Phone = serializers.IntegerField()
    Top = serializers.BooleanField(default=False)
    Highlight = serializers.BooleanField(default=False)
    Vip = serializers.BooleanField(default=False)

    def create(self, validated_data):
        return Product.objects.create(**validated_data)

    def update(self, instance, validated_data):
        instance.IdProduct = validated_data.get('IdProduct', instance.IdProduct)
        instance.State = validated_data.get('State', instance.State)
        instance.AdType = validated_data.get('AdType', instance.AdType)
        instance.Price = validated_data.get('Price', instance.Price)
        instance.Style = validated_data.get('Style', instance.Style)
        instance.Clothing = validated_data.get('Clothing', instance.Clothing)
        instance.Shoes = validated_data.get('Shoes', instance.Shoes)
        instance.Size = validated_data.get('Size', instance.Size)
        instance.MaleFemale = validated_data.get('MaleFemale', instance.MaleFemale)
        instance.Height = validated_data.get('Height', instance.Height)
        instance.Color = validated_data.get('Color', instance.Color)
        instance.Photo_1 = valudated_data.get('Photo_1', instance.Photo_1)
        instance.Photo_2 = valudated_data.get('Photo_2', instance.Photo_2)
        instance.Photo_3 = valudated_data.get('Photo_3', instance.Photo_3)
        instance.Photo_4 = valudated_data.get('Photo_4', instance.Photo_4)
        instance.Photo_5 = valudated_data.get('Photo_5', instance.Photo_5)
        instance.Photo_6 = valudated_data.get('Photo_6', instance.Photo_6)
        instance.Photo_7 = valudated_data.get('Photo_7', instance.Photo_7)
        instance.Photo_8 = valudated_data.get('Photo_8', instance.Photo_8)
        instance.Photo_9 = valudated_data.get('Photo_9', instance.Photo_9)
        instance.Photo_10 = valudated_data.get('Photo_10', instance.Photo_10)
        instance.Photo_11 = valudated_data.get('Photo_11', instance.Photo_11)
        instance.Photo_12 = valudated_data.get('Photo_12', instance.Photo_12)
        instance.Photo_13 = valudated_data.get('Photo_13', instance.Photo_13)
        instance.Photo_14 = valudated_data.get('Photo_14', instance.Photo_14)
        instance.Photo_15 = valudated_data.get('Photo_15', instance.Photo_15)
        instance.Photo_16 = valudated_data.get('Photo_16', instance.Photo_16)
        instance.Photo_17 = valudated_data.get('Photo_17', instance.Photo_17)
        instance.Photo_18 = valudated_data.get('Photo_18', instance.Photo_18)
        instance.Photo_19 = valudated_data.get('Photo_19', instance.Photo_19)
        instance.Photo_20 = valudated_data.get('Photo_20', instance.Photo_20)
        instance.Photo_21 = valudated_data.get('Photo_21', instance.Photo_21)
        instance.Photo_22 = valudated_data.get('Photo_22', instance.Photo_22)
        instance.Photo_23 = valudated_data.get('Photo_23', instance.Photo_23)
        instance.Photo_24 = valudated_data.get('Photo_24', instance.Photo_24)
        instance.Photo_25 = valudated_data.get('Photo_25', instance.Photo_25)
        instance.Photo_26 = valudated_data.get('Photo_26', instance.Photo_26)
        instance.Photo_27 = valudated_data.get('Photo_27', instance.Photo_27)
        instance.Photo_28 = valudated_data.get('Photo_28', instance.Photo_28)
        instance.Photo_29 = valudated_data.get('Photo_29', instance.Photo_29)
        instance.Photo_30 = valudated_data.get('Photo_30', instance.Photo_30)
        instance.Video = validated_data.get('Video', instance.Video)
        instance.Phone = validated_data.get('Phone', instance.Phone)
        instance.Location = validated_data.get('Location', instance.Location)
        instance.Top = validated_data.get('Top', instance.Top)
        instance.Highlight = validated_data.get('Highlight', instance.Highlight)
        instance.Vip = validated_data.get('Vip', instance.Vip)
        instance.save()
        return instance
