# Generated by Django 3.2.9 on 2021-11-25 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListOfAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdList', models.CharField(default='', max_length=20)),
                ('NameOfAnnouncement', models.CharField(max_length=100)),
                ('CreateDate', models.DateTimeField(default=datetime.datetime(2021, 11, 25, 21, 20, 13, 362459))),
                ('EndDate', models.DurationField(default=datetime.datetime(2021, 12, 9, 21, 20, 13, 362482))),
                ('Name', models.CharField(max_length=20)),
                ('Location', models.CharField(default='', max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('Price', models.FloatField(default=0)),
                ('Photos', models.FileField(default=0, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IdPerson', models.CharField(default='', max_length=20)),
                ('Surname', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Patronymic', models.CharField(max_length=20)),
                ('Phone', models.CharField(max_length=15)),
                ('Mail', models.EmailField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('Viber', models.BooleanField(default=False)),
                ('Telegram', models.BooleanField(default=False)),
                ('Whatsapp', models.BooleanField(default=False)),
                ('Location', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
