# Generated by Django 3.2.9 on 2021-11-29 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofannouncement',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 29, 12, 47, 50, 324251)),
        ),
        migrations.AlterField(
            model_name='listofannouncement',
            name='EndDate',
            field=models.DurationField(default=datetime.datetime(2021, 12, 13, 12, 47, 50, 324281)),
        ),
    ]
