# Generated by Django 3.2.9 on 2021-11-30 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211129_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofannouncement',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 11, 27, 2, 528179)),
        ),
        migrations.AlterField(
            model_name='listofannouncement',
            name='EndDate',
            field=models.DurationField(default=datetime.datetime(2021, 12, 14, 11, 27, 2, 528203)),
        ),
    ]
