# Generated by Django 3.2.9 on 2021-12-01 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20211130_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listofannouncement',
            name='CreateDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 1, 16, 59, 47, 947918)),
        ),
        migrations.AlterField(
            model_name='listofannouncement',
            name='EndDate',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 15, 16, 59, 47, 947955)),
        ),
    ]
